language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

sudo: false

before_install:
  - composer config -g github-oauth.github.com $CI_USER_TOKEN

install:
  - composer install --prefer-source

script: phpunit
