language: php

php:
  - 7.0
  - 7.1
  - 7.2

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer config -g github-oauth.github.com $CI_USER_TOKEN
  - if [[ $TRAVIS_PHP_VERSION != 7.2 ]] ; then phpenv config-rm xdebug.ini; fi
  - travis_retry composer self-update

install:
  - travis_retry composer update --no-interaction --prefer-dist

script: vendor/bin/phpunit
